"""Add pricing fields to hall

Revision ID: ac27535d3af4
Revises: 7a715e04a639
Create Date: 2025-11-26 11:19:01.713658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac27535d3af4'
down_revision: Union[str, Sequence[str], None] = '7a715e04a639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.Float(), nullable=False))
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'hall_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('halls', sa.Column('price_per_hour', sa.Float(), nullable=False))
    op.add_column('halls', sa.Column('price_per_day', sa.Float(), nullable=False))
    op.add_column('halls', sa.Column('weekend_price_multiplier', sa.Float(), nullable=False))
    op.add_column('halls', sa.Column('security_deposit', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('halls', 'security_deposit')
    op.drop_column('halls', 'weekend_price_multiplier')
    op.drop_column('halls', 'price_per_day')
    op.drop_column('halls', 'price_per_hour')
    op.alter_column('bookings', 'hall_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###
